repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      args: ["--line-length", "120"]

- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
    - id: isort
      args: ["--profile", "black"]
