version: '3.8'

services:
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        volumes:
            - ../:/app
            - static_volume:/app/static
        ports:
            - 8000:8000
        stdin_open: true
        tty: true
        env_file: .env.${ENVIRON}
        depends_on:
            - db
            - cache
        restart: unless-stopped
    cache:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        ports:
            - 6379:6379
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=challenge
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
volumes:
    postgres_data:
    static_volume:
