name: Tests CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.15]

    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-redis@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run migrations
      run:
        python3 manage.py makemigrations && python3 manage.py migrate
    - name: Run Tests
      run: |
        python3 manage.py test
